### ISSUE TITLE
Como usar?

### ISSUE THREAD

**Issue by joaochris** [edunsouza/zoom-custom-features#1]
Pode me explicar como uso ?

**Comment by edunsouza** [comment]
Oi João! Tudo bem?

Para usar esse script basta inserir o código no console do navegador
(recomendado: Google Chrome) enquanto estiver em uma sala do zoom.

Percebi tuas threads em outros repositórios e vi que tu tem uma dúvida
sobre automatizar o spotlight. Eu posso te ajudar com isso, se tiver
interesse.

Respondendo essa tua outra *thread*: sim, tem como criar um script para
isso. Se tiver interesse, te explico o passo a passo.

> joaochris <https://github.com/joaochris> commented 15 hours ago
> Is there a way to create a script to spotlight videos in the zoom? To facilitate with keyboard shortcuts.



Tu desenvolve em JavaScript? Posso te mostrar como reutilizar esse
repositório.

Cheers!

Em dom., 21 de mar. de 2021 às 18:57, joaochris ***@***.***>
escreveu:

**Comment by joaochris** [comment]
Olá, tudo bem! Obrigado!

Que bom que você encontrou hahah, procuro isso a muito tempo.
Se puder me explicar fico grato, preciso muito disso pra automatizar nossas reuniões que são bem dinâmicas.

Não entendo nada sobre Java Script kkkk.

**Comment by edunsouza** [comment]
Sem problemas!

Me explica o que tu precisa. Se quiser podemos agendar uma call no zoom pra conversar direitinho. Tu tem disponibilidade?

Esse script é usado nas reuniões das Testemunhas de Jeová e serve pra automatizar o zoom de acordo com essas reuniões que também são diferentes do modelo normal.

Abaixo está a lista de features que já implementei (aceito sugestões):

- Focus on President, Conductor, Reader, Speaker and other default roles
- Create custom focus button
- Delete custom focus button
- Call participant before focus time (open video and mic only, nothing more)
- Comments manager (highlight all hands, open the selected mic and lower others' hands)
- Lower all hands button
- Close all mics from participants with video off
- Participants count (people per device, using pattern: "(# of people) - Name(s)" )
- Naming validation
- Waiting room free pass
- Auto remove spotlights
- Auto request video + mic from participants with "ok" flag on name
- Override default focus buttons' targets
- Status logs (running methods, invalid names, opened videos and mics)
- Send email with participants count (using Vercel serverless functions and Sengrid)
- Turn off all videos and microphones (auto disable the option to allow participant to open its own mic)
- Turn on all videos and microphones (auto enable the option to allow participant to open its own mic)
- Turn on all microphones for claps time (turns off after custom timeout)

**Comment by joaochris** [comment]
Caramba hahaha eu sou testemunha de jeová também hahaha. Que dahora, tava procurando essas funções mesmo. Estou disponível para call sim. Se você puder me mostrar na prática essas funções citadas, e como implementar o de spotlight agradeço!

Me manda um email: contatojoaochris@gmail.com

**Comment by edunsouza** [comment]
hahaha eu imaginei que fosse quando falou "nossas reuniões" 😄 

Tenho outro app que é pra designações também, de repente o pessoal da tua congregação tenha interesse.
Te mando email e a gente conversa.

Cheers!

**Comment by edunsouza** [comment]
@joaochris script customizado criado na branch [porto-seguro](https://raw.githubusercontent.com/edunsouza/zoom-custom-features/porto-seguro/zoom-custom-features.js).

Estarei disponível para atuar em futuras issues caso reporte-as.

Vou encerrar essa. Obrigado!
